import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

// 实践经历侧边栏，独立于全栈教程
const sidebars: SidebarsConfig = {
  practiceSidebar: [{type: 'autogenerated', dirName: '.'}],
};

export default sidebars;
