import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

// 工具使用（本地工具）侧边栏，独立于全栈教程
const sidebars: SidebarsConfig = {
  toolsSidebar: [{type: 'autogenerated', dirName: '.'}],
};

export default sidebars;
